# Public entry point for @neevai/sdk. Re-exports the client, resource types,
# the Sandbox handle, and the typed error hierarchy.

from neevai.client import AsyncNeevAI, NeevAI
from neevai.errors import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    DeadlineExceededError,
    InternalServerError,
    NeevAIError,
    NotFoundError,
    PermissionDeniedError,
    PreconditionFailedError,
    RateLimitError,
)
from neevai.handles import AsyncSandbox, Sandbox
from neevai.runtime import (
    AsyncProcess,
    AsyncSandboxConnection,
    AsyncSandboxFiles,
    AsyncSandboxProcesses,
    Process,
    SandboxConnection,
    SandboxFiles,
    SandboxProcesses,
)
from neevai.transport.lifecycle import AsyncRawClient, RawClient
from neevai.types import (
    CreateSnapshotParams,
    ProcessInfo,
    ProcessLogsPage,
    ProcessStatus,
    Scope,
    Signal,
    Snapshot,
    SnapshotListResponse,
    SnapshotStatus,
)

__all__ = [
    "NeevAI",
    "AsyncNeevAI",
    "RawClient",
    "AsyncRawClient",
    "Sandbox",
    "AsyncSandbox",
    "SandboxConnection",
    "AsyncSandboxConnection",
    "SandboxFiles",
    "AsyncSandboxFiles",
    "SandboxProcesses",
    "AsyncSandboxProcesses",
    "Process",
    "AsyncProcess",
    "Signal",
    "ProcessStatus",
    "ProcessInfo",
    "ProcessLogsPage",
    "Scope",
    "Snapshot",
    "SnapshotStatus",
    "CreateSnapshotParams",
    "SnapshotListResponse",
    "NeevAIError",
    "APIConnectionError",
    "APITimeoutError",
    "APIError",
    "BadRequestError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "ConflictError",
    "PreconditionFailedError",
    "RateLimitError",
    "DeadlineExceededError",
    "InternalServerError",
]
